### ISSUE TITLE
SS-13: Remove SMILES fails 

### ISSUE THREAD

**Issue by Sulstice** [Global-Chem/Mother-Nature#25]
The Remove SMILES fails because there is no label to the channel that the user is removing the SMILES from. 

```yml

  remove_chemical:
      if: github.event.label.name == 'remove_chemical'
      runs-on: "ubuntu-latest"
      env:
        GITHUB_TOKEN: ${{ secrets.ISSUE_TOKEN }}
      permissions:

```

The remove chemical command should be `remove_chemical_cannabis` and this command should be in every github action workflow.
